import {test,expect,type Page} from '@playwright/test';
import {readFileSync} from 'node:fs';
import {PrismaClient} from '@prisma/client';
const db=new PrismaClient({datasourceUrl:process.env.TEST_DATABASE_URL});
const day=(n:number)=>{const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());return new Date(Date.parse(today+'T00:00:00Z')+n*86400000).toISOString().slice(0,10);};
const start=day(2),end=day(5);
async function login(page:Page){const {password}=JSON.parse(readFileSync('.e2e-runtime/session.json','utf8'));await page.goto('/admin');await page.getByLabel('Password',{exact:true}).fill(password);await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page.getByRole('heading',{name:'Properties',exact:true})).toBeVisible();}
async function dates(page:Page){await page.getByRole('button',{name:/Check-in · Check-out/}).click();for(const date of [start,end]){const cell=page.getByRole('button',{name:date,exact:true});if(!await cell.isVisible())await page.getByRole('button',{name:'Next month'}).click();await cell.click();}await page.getByRole('button',{name:'Apply Dates'}).click();}
async function addTestPhoto(propertyId:string){await db.propertyMedia.create({data:{propertyId,cloudinaryPublicId:`test/${propertyId}`,secureUrl:'https://res.cloudinary.com/modern-airbnd-test/image/upload/fixture.png',format:'png',width:640,height:480,bytes:100,altText:'Test fixture, not a real property photograph',isCover:true}});}
test.beforeEach(async({page})=>{await page.route('https://res.cloudinary.com/**',route=>route.fulfill({contentType:'image/png',body:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=','base64')}));});
test.afterAll(async()=>db.$disconnect());
test('mobile public discovery, range calendar, passport and correct enquiry CTA',async({page})=>{
 await page.goto('/');await expect(page.locator('.hero-visual')).toBeVisible();await page.getByRole('button',{name:/Where would you like to stay/}).click();await page.getByRole('button',{name:/Test Gurgaon/}).click();await dates(page);await page.getByRole('button',{name:'Check Availability',exact:true}).click();await expect(page.getByRole('heading',{name:'Available stays',exact:true})).toBeVisible();await page.getByRole('link',{name:'View Property',exact:true}).click();await expect(page.getByRole('heading',{name:'Property Passport'})).toBeVisible();await expect(page.locator('.mobile-sticky').getByRole('link',{name:'Enquire on WhatsApp'})).toHaveAttribute('href',/wa.me/);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
});
test('no dates and unavailable dates recover through the date calendar',async({page})=>{
 const p=await db.property.findUniqueOrThrow({where:{slug:'test-garden-apartment'},include:{units:true}});
 await page.goto('/properties/test-garden-apartment');await expect(page.locator('.mobile-sticky').getByRole('button',{name:'Check Availability'})).toBeVisible();
 const b=await db.availabilityBlock.create({data:{unitId:p.units[0].id,startDate:new Date(start),endDate:new Date(end)}});
 try{await page.goto(`/properties?location=test-gurgaon&checkIn=${start}&checkOut=${end}`);await expect(page.getByRole('heading',{name:'Unavailable for your dates',exact:true})).toBeVisible();await page.getByRole('link',{name:'View Property',exact:true}).click();await page.locator('.mobile-sticky').getByRole('button',{name:'Change Dates'}).click();await expect(page.getByRole('dialog')).toBeVisible();await page.getByRole('button',{name:'Clear dates'}).click();}finally{await db.availabilityBlock.delete({where:{id:b.id}});}
});
test('guided owner draft, room inventory, private preview, publish and all-room blocking',async({page,request})=>{
 await login(page);await page.getByRole('button',{name:'Add Property',exact:true}).click();await page.getByLabel('Property name',{exact:true}).fill('Test Three Room Stay');await page.getByLabel(/^Description/).fill('An end-to-end test property used to verify rooms and publication.');await page.getByRole('button',{name:'Save Draft',exact:true}).click();await expect(page.getByText('Property saved.',{exact:true})).toBeVisible();
 const property=await db.property.findUniqueOrThrow({where:{slug:'test-three-room-stay'}});expect((await request.get('/api/v1/properties/test-three-room-stay')).status()).toBe(404);
 await page.getByRole('button',{name:/3How guests stay/}).click();await page.getByRole('button',{name:'Individual rooms',exact:true}).click();await expect(page.getByRole('button',{name:'Add room',exact:true})).toBeVisible();
 for(const name of ['Room 101','Room 102','Room 103']){await page.getByLabel('Room name',{exact:true}).fill(name);await page.getByRole('button',{name:'Add room',exact:true}).click();await expect(page.getByRole('button',{name,exact:true})).toBeVisible();}
 await addTestPhoto(property.id);await page.reload();await page.getByRole('button',{name:'Edit',exact:true}).filter({visible:true}).last().click();
 // Select the specific card after sorting by most recently updated.
 if(!await page.getByRole('heading',{name:'Test Three Room Stay',exact:true}).isVisible()){await page.getByRole('button',{name:'Back to properties'}).click();await page.locator('article').filter({has:page.getByRole('heading',{name:'Test Three Room Stay'})}).getByRole('button',{name:'Edit',exact:true}).click();}
 await page.getByRole('button',{name:/8Preview & publish/}).click();await page.getByRole('button',{name:'Preview as Guest'}).click();await expect(page.getByRole('dialog')).toBeVisible();expect((await request.get('/api/v1/properties/test-three-room-stay')).status()).toBe(404);await page.getByRole('button',{name:'Close dialog'}).click();await page.getByRole('button',{name:'Check readiness'}).click();await expect(page.getByText('All required publication checks passed.')).toBeVisible();await page.getByRole('button',{name:'Publish Property',exact:true}).click();await expect(page.getByText('Property published.',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:/9Availability/}).click();
 for(const [i,name] of ['Room 101','Room 102','Room 103'].entries()){await page.getByRole('button',{name,exact:true}).click();await page.getByLabel('Unavailable from').fill(start);await page.getByLabel('Reopens on').fill(end);await page.getByRole('button',{name:'Block Dates',exact:true}).click();await expect(page.getByText('Dates blocked successfully.',{exact:true})).toBeVisible();const response=await request.get(`/api/v1/properties/test-three-room-stay?checkIn=${start}&checkOut=${end}`);expect((await response.json()).data.availability.status).toBe(i<2?'AVAILABLE':'UNAVAILABLE');}
});
